spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@180.108.205.115:18083:XFYW
          username: xsm_sys
          password: Xsm_sys_2023
        xsm_biz:
          driver-class-name: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@180.108.205.115:18083:XFYW
          username: xsm_biz
          password: Xsm_biz_2023
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 5
    # 连接超时时间
    timeout:
    # 设置密码
    password:

mybatis-plus:
  # mybatis xml配置文件扫描
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.savage.entity
  global-config:
    db-column-underline: true
    db-config:
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      #数据库大写下划线转换
      #capital-mode: true
      #驼峰下划线转换
      db-column-underline: true
  configuration:
    #打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

logging:
  level:
    com.baomidou.samples.metainfo: debug
